### ISSUE TITLE
allow_maxshield = True for Elekta data

### ISSUE THREAD

**Issue by SophieHerbst** [nih-megcore/enigma_anonymization_lite#4]
Hi everyone, first of all I wanted to say that the tools are very easy to work with! 

While working on the conversion of our data, I had an error when trying to import the raw .fif files, because the data were recorded under active shielding. The error can be fixed by adding the input parameter 'allow_maxshield'=True in the corresponding function in enigma_anonymization_lite_functions.py. But then I have always been instructed that maxfilter should be applied to those data to avoid distortion. 

```
# function to read the MEG scans into mne python for processing

def read_meg(meg_fname):

    if meg_fname[-1]==os.path.sep:
        meg_fname=meg_fname[:-1]
    path, ext = os.path.splitext(meg_fname)
    if ext == '.fif':
        return mne.io.read_raw_fif(meg_fname, allow_maxshield=True) 
```

**Comment by nugenta** [comment]
Thanks for the kudos! I fixed this.
