### ISSUE TITLE
Could not load any valid 3D backend

### ISSUE THREAD

**Issue by SophieHerbst** [nih-megcore/enigma_anonymization_lite#5]
Hello again, 
I had another small error that I thought might be useful to report. I installed the enigma tools into a new conda environment, and got an error for lacking a valid 3D backend. 
'pip install pyvistaqt' fixed it. 

> /home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/enigma_anonymization_lite/enigma_anonymization_lite_functions.py:382: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
>   return mne.io.read_raw_fif(meg_fname, allow_maxshield=True) # sh 20230523
>     Range : 33000 ... 578999 =     16.500 ...   289.500 secs
> Ready.
> 2023-05-23 12:44:23,852 : INFO : Running QA report
> 2023-05-23 12:44:33,360 : ERROR : make_QA_report:
> Could not load any valid 3D backend
> pyvistaqt: No module named 'pyvistaqt'
> notebook: No module named 'ipywidgets'
> 
>  install pyvistaqt, using pip or conda:
> 'pip install pyvistaqt'
> 'conda install -c conda-forge pyvistaqt'
> 
>  or install ipywidgets, if using a notebook backend
> 'pip install ipywidgets'
> 'conda install -c conda-forge ipywidgets'
> Traceback (most recent call last):
>   File "/home/sh254795/anaconda3/envs/enigma/bin/enigma_anonymization_mne.py", line 107, in <module>
>     loop_QA_report(dframe, subjects_dir=subjects_dir, topdir=topdir, bidsonly=bidsonly)
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/enigma_anonymization_lite/enigma_anonymization_lite_functions.py", line 540, in loop_QA_report
>     fig = mne.viz.plot_alignment(info=raw.info, trans=trans, subject=subject,
>   File "<decorator-gen-130>", line 12, in plot_alignment
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/mne/viz/_3d.py", line 890, in plot_alignment
>     renderer = _get_renderer(
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/mne/viz/backends/renderer.py", line 49, in _get_renderer

**Comment by nugenta** [comment]
Thanks for the catch! I added pyvistaqt to the requirements.txt file.

**Comment by SophieHerbst** [comment]
thank you!
