### ISSUE TITLE
error when producing plots

### ISSUE THREAD

**Issue by SophieHerbst** [nih-megcore/enigma_anonymization_lite#6]
Hello again,
I am running into an error that I am not sure how to fix, during the call to:  mne.viz.plot_alignment
The figure pops up, I have to close it manually, and then it breaks: 
Also, could you set the plotting functions to block=False?

> /home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/pyvista/plotting/plotting.py:6643: UserWarning: Not within a jupyter notebook environment.
> Ignoring ``jupyter_backend``.
>   warnings.warn(
> 2023-05-26 11:07:31,810 : ERROR : make_QA_report: 
> 'NoneType' object has no attribute 'layout'
> Using outer_skin.surf for head surface.
> Getting helmet for system 306m
> Channel types::	grad: 204, mag: 102
> HBox(children=(Text(value='', layout=Layout(margin='2px 0px 2px 0px', min_width='0px'), placeholder='Type a file name'), Button(icon='camera', layout=Layout(margin='2px 0px 2px 0px', min_width='0px'), style=ButtonStyle(), tooltip='Take a screenshot')))
> /home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/pyvista/plotting/plotting.py:6643: UserWarning: Not within a jupyter notebook environment.
> Ignoring ``jupyter_backend``.
>   warnings.warn(
> Traceback (most recent call last):
>   File "/home/sh254795/anaconda3/envs/enigma/bin/enigma_anonymization_mne.py", line 107, in <module>
>     loop_QA_report(dframe, subjects_dir=subjects_dir, topdir=topdir, bidsonly=bidsonly)
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/enigma_anonymization_lite/enigma_anonymization_lite_functions.py", line 540, in loop_QA_report
>     fig = mne.viz.plot_alignment(info=raw.info, trans=trans, subject=subject, 
>   File "<decorator-gen-130>", line 12, in plot_alignment
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/mne/viz/_3d.py", line 1014, in plot_alignment
>     renderer.show()
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/mne/viz/backends/_notebook.py", line 1570, in show
>     viewer.layout.width = None  # unlock the fixed layout
> AttributeError: 'NoneType' object has no attribute 'layout'

**Comment by SophieHerbst** [comment]
update: running the command with xvfb-run fixes the problem

**Comment by nugenta** [comment]
We really do appreciate your help in debugging on different systems! And sorry for all the kinks. The MNE visualization are always tricky to get running correctly, although I'm confused why it seems to be trying to use the notebook backend. Perhaps I can add a command line argument for backend that defaults to something more appropriate. Are you by any chance trying to run remotely on a server?

**Comment by SophieHerbst** [comment]
Thank you for your reply. Yes, due to the IT architecture here my machine is effectively a server. But it runs now.

**Comment by SophieHerbst** [comment]
Unfortunately, I am still stuck with the error pasted below.

When running  the code with xvfb-run, there are no errors, but it gets stuck at some point, presumably when a figure is plotted, but do not show up, which prevents the script from continuing. 

Do you have any suggestion on how to edit the code to prevent these problems?


> /home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/pyvista/plotting/plotting.py:6643: UserWarning: Not within a jupyter notebook environment.
> Ignoring ``jupyter_backend``.
>   warnings.warn(
> 2023-06-13 11:13:11,077 : ERROR : make_QA_report: 
> 'NoneType' object has no attribute 'layout'
> Using outer_skin.surf for head surface.
> Getting helmet for system 306m
> Channel types::	grad: 204, mag: 102
> HBox(children=(Text(value='', layout=Layout(margin='2px 0px 2px 0px', min_width='0px'), placeholder='Type a file name'), Button(icon='camera', layout=Layout(margin='2px 0px 2px 0px', min_width='0px'), style=ButtonStyle(), tooltip='Take a screenshot')))
> /home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/pyvista/plotting/plotting.py:6643: UserWarning: Not within a jupyter notebook environment.
> Ignoring ``jupyter_backend``.
>   warnings.warn(
> Traceback (most recent call last):
>   File "/home/sh254795/anaconda3/envs/enigma/bin/enigma_anonymization_mne.py", line 107, in <module>
>     loop_QA_report(dframe, subjects_dir=subjects_dir, topdir=topdir, bidsonly=bidsonly)
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/enigma_anonymization_lite/enigma_anonymization_lite_functions.py", line 540, in loop_QA_report
>     fig = mne.viz.plot_alignment(info=raw.info, trans=trans, subject=subject, 
>   File "<decorator-gen-130>", line 12, in plot_alignment
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/mne/viz/_3d.py", line 1014, in plot_alignment
>     renderer.show()
>   File "/home/sh254795/anaconda3/envs/enigma/lib/python3.10/site-packages/mne/viz/backends/_notebook.py", line 1570, in show
>     viewer.layout.width = None  # unlock the fixed layout
> AttributeError: 'NoneType' object has no attribute 'layout'

**Comment by nugenta** [comment]
@jstout211 has also been working on this... it's a chronic problem with MNE python and client/server architecture. My first question - do you use MNE python for your own analyses? And if so, is there a particular backend you choose for visualization? I think that part of the problem might be that it's trying to invoke a jupyter notebook backend for the visualizations. I'm not sure why it's doing that, and I'll look into forcing a different backend and see if that helps.

**Comment by nugenta** [comment]
Okay, so I updated it to select the pyvistaqt backend - Can you see what that does? If you are on a client connected to a server, I suspect you will still need to invoke the virtual frame buffer with xvfb-run.

**Comment by SophieHerbst** [comment]
Thank you for your reply! I do use mne (currently 1.3.1 installed with conda), with pyvista:
pyvista:          0.38.5 {OpenGL 4.5.0 NVIDIA 390.157 via NVS 315/PCIe/SSE2}
pyvistaqt:        0.0.0
But I created a separated environment to install the enigma tools. 

I updated the enigma tools and am currently running it again, will let you know if it works!

**Comment by jstout211** [comment]
@SophieHerbst - I added some options to the makefile to test the full pipeline + rendering.  If your most recent run works, then you can ignore the rest of this message.

But if it fails, can you download the new updates, then run `make install_test; make test_headless`.  This assumes that the environment has conda/ mamba / freesurfer  installed. The make install_test runs the below - and the test_headless runs pytest in the new environment with the test data.  The output html file will be in /tmp/pytest-of-<<USERNAME>>/pytest-current/bidscurrent/bids_out/derivatives/BIDS_ANON_QA/Coreg_QA_report.html .  And hopefully the test doesn't fail.

```
	conda env remove -n enigma_meg_test   #Remove test environment if present
	mamba create --override-channels --channel=conda-forge --name=enigma_meg_test mne pip -y   #Install MNE in test env
	mamba install --name=enigma_meg_test -c conda-forge "vtk>=9.2=*osmesa*" "mesalib=21.2.5" -y  #Install headless options
	($(CONDA_ACTIVATE) enigma_meg_test ; pip install -e .; pip install pytest pytest-reportlog )  #Install this code and pytest
	git submodule init  
	git pull --recurse-submodules  #Downloads test data
```

**Comment by SophieHerbst** [comment]
It works, I only had to pip install pyqt5 in the same environment.
thank you for your help!

**Comment by jstout211** [comment]
@SophieHerbst - glad that this works.  Appreciate all of the troubleshooting on your part.  Will close this issue now.
