### ISSUE TITLE
mne version

### ISSUE THREAD

**Issue by mschendel** [nih-megcore/enigma_anonymization_lite#7]
Hi all,
I'm getting ready to start working on some of our data.  What version of mne does this require?  I have an environment with mne1.3 that I've used for mne_bids before, wondering if that is sufficient.

Thanks,
Megan

**Comment by mschendel** [comment]
Hi all,
I looked more closely at the instructions, and I tried the conda environment creation.  So I see the version of mne installed is currently 1.6.0.  Makes sense!  Thanks.

**Comment by nugenta** [comment]
Glad you figured it out! Let us know if you have any other issues!
